apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wrenchbox
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-deployment.yaml
  - mailhog-deployment.yaml
  - api-deployment.yaml
  - hpa.yaml
