apiVersion: v1
kind: Secret
metadata:
  name: wrenchbox-secret
  namespace: wrenchbox
type: Opaque
stringData:
  POSTGRES_DB: wrenchbox
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  Jwt__Secret: WrenchBox_K8s_Secret_Key_Min_32_Chars!!
  Webhook__Secret: dev-webhook-secret
  ConnectionStrings__Default: Host=postgres;Port=5432;Database=wrenchbox;Username=postgres;Password=postgres
